// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDTy6adL-_qlmJnjfh47Gwk21oXRM1Ggp0',
    appId: '1:339620348760:web:8230f39f34612b7659db2d',
    messagingSenderId: '339620348760',
    projectId: 'harmonyhub-cfb3e',
    authDomain: 'harmonyhub-cfb3e.firebaseapp.com',
    storageBucket: 'harmonyhub-cfb3e.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyASaxkgM5HRxYUw5rG7ktWujmC8Did4GJU',
    appId: '1:339620348760:android:273a39394fc4c45159db2d',
    messagingSenderId: '339620348760',
    projectId: 'harmonyhub-cfb3e',
    storageBucket: 'harmonyhub-cfb3e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDUVWqWhhpSwz9SyVDc-l-hoVb2FN6ImMA',
    appId: '1:339620348760:ios:da16b259cd59224d59db2d',
    messagingSenderId: '339620348760',
    projectId: 'harmonyhub-cfb3e',
    storageBucket: 'harmonyhub-cfb3e.appspot.com',
    iosBundleId: 'com.example.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDUVWqWhhpSwz9SyVDc-l-hoVb2FN6ImMA',
    appId: '1:339620348760:ios:5e5f128e3cade16059db2d',
    messagingSenderId: '339620348760',
    projectId: 'harmonyhub-cfb3e',
    storageBucket: 'harmonyhub-cfb3e.appspot.com',
    iosBundleId: 'com.example.app.RunnerTests',
  );
}
